### ISSUE TITLE
ppc-amigaos-as/ld : Fatal error: selected target format 'elf32-amigaos' unknown

### ISSUE THREAD

**Issue by kas1e** [migthymax/binutils-gdb#1]
Topic says it all: I can't compile any object by gas, as it cause this error. Even just running it without arguments, it brings such error:

```
$ ppc-amigaos-as -V
GNU assembler version 2.40.50 (ppc-amigaos) using BFD version (GNU Binutils) 2.40.50.20230106
Assembler messages:
Fatal error: selected target format 'elf32-amigaos' unknown
```

**Comment by kas1e** [comment]
The same happens with "ld" as well. I just build object via gas from public adtools, and then trying to link it with newer ld, and got the same issue:

```
$ ppc-amigaos-ld -N -q test.o -o test
ppc-amigaos-ld: target elf32-amigaos not found
```

**Comment by kas1e** [comment]
I just checked the public adtools repo, and this one, and find out, that in adtools repo, we do have in bfd dir ```elf32-amigaos.c``` file, which compiled in, and used later.  It's mostly a copy of elf32-ppc.c file, but with some other changes on top (probably in terms of relocations, but I am not sure).

**Comment by migthymax** [comment]
Fixed with commit "Selected target format 'elf32-amigaos' unknown"
