### ISSUE TITLE
.rodata should be in independent segment, and marked as R

### ISSUE THREAD

**Issue by kas1e** [migthymax/binutils-gdb#12]
Topic says it all. After discussion, we have on amigans it comes to the point that having .rodata anywhere else but not as it was with previous binutils cause all sort of issues with .sobjs support. The fast-hack of putting .rodata to another bunch of sections in RW segment make .sobjs at least didn't crash right from the start, but still, cause issues.

One of issues, for example, is that our usual small test case having .so and printing info about ctros/dtros are crashes on the elf.library prior 53.37, but works on version later. Explain of this is that prior to elf.library 53.37, __shlib_call_(de)constructors() was called (located in SDK:newlib/shcrtbegin.o). With 53.37 or higher, it doesn't use that anymore and instead directly reads .ctors/.dtors and executes the functions specified there. So, the fact that we have a crash in previous version, when .rodata put in RW segment, one more time point out us that it's wrong and cause issues with .so handling , and .rodata should be placed as before as standalone segment with Read only flag.

So currently i create it as one ticket, in hope that once .rodata will be R and in own segment, then issue with crash prior elf.library 53.37 will gone, but if not, then we can create another ticket about.

**Comment by kas1e** [comment]
With the latest commits, we do have .rodata as a separate segment now.

**Comment by migthymax** [comment]
The current findings are that the .rodata section mus be in it own segment, directly after the segment containing the .text and .plt section. Whereas the .text and .pkt section are the last sections in segment prior to the segment containing the .rodata section. The segment following seems to need the .rodata section as the first one. If other setions can follow the .rodata section is currently unknown.
